### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by aaademosu** [mubrik/sharepoint-WB-timesheet#1]
what does test data access do?
![image](https://user-images.githubusercontent.com/2017630/133252627-f7b1e886-6059-4886-a66a-44477491dce3.png)

Inconsistency in day heading labels
![image](https://user-images.githubusercontent.com/2017630/133252947-f47b565b-15c0-402e-b06e-5affd4c78b81.png)

Adding a new row and changing tab does not keep the state of the row added. Same thing if i select a period and go to drafts tab.
![image](https://user-images.githubusercontent.com/2017630/133254248-ab8e3def-e5a7-440f-97c9-2b0fdcd53f46.png)
![image](https://user-images.githubusercontent.com/2017630/133254295-6405222f-88c3-4c25-bf9c-26bc914fa67c.png)

What is the expected functionality that is to be developed in the drafts tab?

**Comment by mubrik** [comment]
Test data acess, just for logging inputted data to console so i can verify them.
I know about the heading labels, did not use the fucntions for all label as i'm not sure how i want the ordering to be yet(sizing/order of tabs)

**Comment by aaademosu** [comment]
The ordering should not affect the size of the labels. Shouldn't the rendering of the text and ordering be independent activities?

**Comment by mubrik** [comment]
They are, the function for naming the label based on the dates will make the column slightly larger and i dont have much space to play with in the first place hence why i didnt fill it up yet as i'm not even sure i'll keep the function that formats the column label.

The dates beside the day gives the user more information but visually it takes a larger column and i dont want that table to exceed the viewport size of a tab. 

I was going to resize and reorder (maybe throw freshservice column last since its unimportant) before filling out the other labels to see if i have space to work with but i havent gotten to that yet, feel free to tweak it, i just havent gotten back to it is all.

**Comment by aaademosu** [comment]
Ok. Is there no way to resize the columns so as to take advantage of the additional spacing available which i have highlighted.

![image](https://user-images.githubusercontent.com/2017630/133257996-ec9eee6b-994d-49f8-ad10-a5b24adde718.png)

**Comment by mubrik** [comment]
There is, i wanted to leave that for when i was working on the responsiveness on the page so its a bit dynamic, i can adjust them manually tho.

I thouh fabric-react would have its "material" variant of "makeStyles" which would give me access to the CSS breakpoints i need for a responsive table, but apparently its still in Beta? and i dont see any breakpoint object available in the theme props which suck
https://www.npmjs.com/package/@fluentui/make-styles
still looking for a way to go round this
