### ISSUE TITLE
Main and New Page

### ISSUE THREAD

**Issue by aaademosu** [mubrik/sharepoint-WB-timesheet#2]
Can we make use of page real estate by collapsing items rather than render each item to occupy the full width.

![image](https://user-images.githubusercontent.com/2017630/134199062-b553663a-3b64-4826-ae5b-1ed78359bce3.png)

Can we set a default value here.

![image](https://user-images.githubusercontent.com/2017630/134199451-0f038432-4b9a-48fb-b8ad-d399589ca3ac.png)

![image](https://user-images.githubusercontent.com/2017630/134199727-cef85132-ffb4-40b3-a86a-bb17b53c19e2.png)
1. On the image above, it doesn't seem to indicate that the component rendered is a button 
2. The text seems redundant.

**Comment by mubrik** [comment]
Pushed  a change stacking the first filter inputs, will adding additional grouping to the list will be explored.

Added a default value of 1 to input

The select button disabled state was not shown properly due to me experimenting with theming, should be a bit more visible now, also made the select a date label blank as i agree it is redundant
